### ISSUE TITLE
Double check this list of full names and add a PR with those that are confirmed

### ISSUE THREAD

**Issue by toscalix** [scanoss/crypto_algorithms_open_dataset#22]
## Bachground

List of full names:
* [x] 3des - Triple Data Encryption Standard
* [x] 3way - 3-Way Block Cipher
* [x] ASN1 - Abstract Syntax Notation One #20 
* [x] CMAC - Cipher-based Message Authentication Code
* [x] X509 - X.509 Public Key Infrastructure
* [x] aes - Advanced Encryption Standard #21 
* [x] aria - ARIA (block cipher)
* [x] bcrypt - bcrypt Password Hashing
* [x] blakex - BLAKE Hash Function
* [x] blowfish - Blowfish Cipher
* [x] blum-goldwasser - Blum-Goldwasser Probabilistic Encryption
* [x] camellia - Camellia Cipher
* [x] cast - Carlisle Adams and Stafford Tavares (CAST)
* [x] chacha(salsa) - ChaCha/Salsa Stream Cipher
* [x] cmea - Cellular Message Encryption Algorithm
* [x] cms - Cryptographic Message Syntax
* [x] cobra - Cobra Cipher
* [x] crc16 - Cyclic Redundancy Check 16
* [x] crc32 - Cyclic Redundancy Check 32
* [x] dcc - Direct Code Construction
* [x] des - Data Encryption Standard
* [x] desede - Triple Data Encryption Algorithm (3DES)
* [x] dhe - Diffie-Hellman Ephemeral
* [x] dhies - Diffie-Hellman Integrated Encryption Scheme
* [x] diffiehellman - Diffie-Hellman Key Exchange
* [x] dsa - Digital Signature Algorithm
* [x] ecdh - Elliptic-Curve Diffie-Hellman
* [x] ecmqv - Elliptic Curve Menezes-Qu-Vanstone
* [x] elgamal - ElGamal Encryption System
* [x] f8 - F8 Mode of Operation
* [x] fasthash - FastHash Algorithm
* [x] fcrypt - fcrypt Password Hashing
* [x] feal - Fast Data Encipherment Algorithm
* [x] fletcher - Fletcher's Checksum
* [x] fnv1 - Fowler-Noll-Vo Hash Function
* [x] fortuna - Fortuna Random Number Generator
* [x] gea0-x - GPRS Encryption Algorithm
* [x] gost - GOST Block Cipher
* [x] grain - Grain Stream Cipher
* [x] haval - HAVAL Hash Function
* [x] hc128 - HC-128 Stream Cipher
* [x] hc256 - HC-256 Stream Cipher
* [x] ice - ICE (block cipher)
* [x] idea - International Data Encryption Algorithm
* [x] isaac - ISAAC Random Number Generator
* [x] juniper - Juniper Cipher
* [x] kazumi - Kazumi Cipher
* [x] keccak - Keccak Hash Function (SHA-3)
* [x] khazad - Khazad Block Cipher
* [x] loki91 - LOKI91 Block Cipher
* [x] luc - Lucifer Cipher
* [x] lucifer - Lucifer Cipher
* [x] mceliece - McEliece Cryptosystem
* [x] md160 - RIPEMD-160 Hash Function
* [x] md2 - MD2 Hash Function
* [x] md4 - MD4 Hash Function
* [x] md5 - MD5 Hash Function
* [x] md6 - MD6 Hash Function
* [x] mdc2 - MDC-2 Hash Function
* [x] misty1 - MISTY1 Block Cipher
* [x] mqv - Menezes-Qu-Vanstone
* [x] mscash - MSCash Password Hashing
* [x] mscash2 - MSCash2 Password Hashing
* [x] multi2 - MULTI2 Cipher
* [x] nimbus - Nimbus Cipher
* [x] noekeon - NOEKEON Block Cipher
* [x] ntruencrypt - NTRUEncrypt
* [x] panama - PANAMA Hash and Stream Cipher
* [x] pbe - Password-Based Encryption
* [x] pbes1 - Password-Based Encryption Scheme 1
* [x] pbes2 - Password-Based Encryption Scheme 2
* [x] pbkdf1 - Password-Based Key Derivation Function 1
* [x] pbkdf2 - Password-Based Key Derivation Function 2
* [x] pkcs12 - Public Key Cryptography Standards #12
* [x] pkcs7 - Public Key Cryptography Standards #7
* [x] quad - Quad Cipher
* [x] rabbit - Rabbit Stream Cipher
* [x] rabin - Rabin Encryption Algorithm
* [x] rc2 - RC2 Block Cipher
* [x] rc4-hmac - RC4 with HMAC
* [x] rc4 - RC4 Stream Cipher
* [x] rc5 - RC5 Block Cipher
* [x] rc6 - RC6 Block Cipher
* [x] rijndael - Rijndael Cipher
* [x] ripemd - RIPEMD Hash Function
* [x] rsa-oaep - RSA with Optimal Asymmetric Encryption Padding
* [x] rsa - RSA Encryption Algorithm
* [x] salsa10 - Salsa10 Stream Cipher
* [x] salsa20 - Salsa20 Stream Cipher
* [x] sapphire - SAPPHIRE Cipher
* [x] seal - SEAL Stream Cipher
* [x] seed - SEED Block Cipher
* [x] serpent - Serpent Block Cipher
* [x] shacal - SHACAL Block Cipher
* [x] shark - SHARK Block Cipher
* [x] shax - SHA-x (SHA-1, SHA-256, etc.)
* [x] shs - Secure Hash Standard
* [x] skein - Skein Hash Function
* [x] skipjack - Skipjack Block Cipher
* [x] sms4 - SMS4 Block Cipher
* [x] snerfu - SNERFU Hash Function
* [x] snow - SNOW Stream Cipher
* [x] sober - SOBER Stream Cipher
* [x] sosemanuk - SOSEMANUK Stream Cipher
* [x] srp - Secure Remote Password Protocol
* [x] ssha - Salted Secure Hash Algorithm
* [x] tcrypt - TCRYPT Encryption
* [x] tdes - Triple Data Encryption Standard
* [x] tea - Tiny Encryption Algorithm
* [x] threefish - Threefish Block Cipher
* [x] tiger - Tiger Hash Function
* [x] tnepres - TNEPRES (Reverse Serpent)
* [x] twofish - Twofish Block Cipher
* [x] vmpc - VMPC Stream Cipher
* [x] wake - WAKE Stream Cipher
* [x] whirpool - Whirlpool Hash Function
* [x] xtea - eXtended Tiny Encryption Algorithm
* [x] xtr - XTR Public Key System
* [x] yarrow - Yarrow Random Number Generator
* [x] zipcrypt - ZipCrypt Encryption
* [x] zuc - ZUC Stream Cipher

## Description

* Double check the above names
* Those that are correct and there is a merged PR, should be checked.
* Those that are wrong or make no sense should be corrected in a comment and a PR should be created and merged.
* [  ] The above list have been fully evaluated and the corresponding confirmed full names added to the crypto algorithm description.
* [  ] The full names has been submitted to SPDX

**Comment by scanossjeronimo** [comment]
Solved this issue on #23
